import Head from "next/head";
import { observer, useLocalObservable } from "mobx-react-lite";
import PageData from "../store/PageData";
import HeaderComp from "../components/HeaderComp";
import BreadCrumbComp from "../components/BreadCrumbComp";
import Banner from "../components/Banner";
import TableOfContents from "../components/TableOfContents";
import Contents from "../components/Contents";
import FooterComp from "../components/FooterComp";

const Home = () => {
  return (
    <div>
      <Head>
        <title>CryptoXpress Technical Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeaderComp />
        <BreadCrumbComp />
        <Banner />
        <div className="mainContainer">
          <TableOfContents />
          <Contents />
        </div>
      </main>
      <FooterComp />
    </div>
  );
};

export default Home;
